yatube/about/urls.py
from django.urls import path

from . import views


app_name = 'about'

urlpatterns = [
    path('author/', views.AboutAuthorView.as_view(), name='author'),
    path('tech/', views.AboutTechView.as_view(), name='tech'),
]

yatube/posts/urls.py
from django.urls import path

from . import views


app_name = 'posts'
urlpatterns = [
    path('', views.index, name=''),
    path('index/', views.index, name='index'),
    path('groups/', views.groups, name='groups'),
    path('group/<slug:slug>/', views.group_list, name='group_list'),
    path('profile/<str:username>/', views.profile, name='profile'),
    path('posts/<int:post_id>/', views.post_detail, name='post_detail'),
    path('posts/<int:post_id>/edit/', views.post_edit, name='post_edit'),
    path('posts/<int:post_id>/comment', views.add_comment, name='add_comment'),
    path('create/', views.post_create, name='post_create'),
    path('follow/', views.follow_index, name='follow_index'),
    path(
        'profile/<str:username>/follow/',
        views.profile_follow,
        name='profile_follow'
    ),
    path(
        'profile/<str:username>/unfollow/',
        views.profile_unfollow,
        name="profile_unfollow"
    ),
]

yatube/yatube/urls.py
from django.contrib import admin
from django.urls import include, path
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('admin/', admin.site.urls),
    path('auth/', include('users.urls', namespace='users')),
    path('auth/', include('django.contrib.auth.urls')),
    path('', include('posts.urls', namespace='posts')),
    path('about/', include('about.urls', namespace='about')),
]

handler404 = 'core.views.page_not_found'
handler500 = 'core.views.server_error'
handler403 = 'core.views.permission_denied'

if settings.DEBUG:
    urlpatterns += static(
        settings.MEDIA_URL, document_root=settings.MEDIA_ROOT
    )

yatube/posts/models.py
from django.db import models
from django.contrib.auth import get_user_model


User = get_user_model()


class Group(models.Model):
    title = models.CharField('Группа', max_length=200)

    slug = models.SlugField('Идентификатор',
                            unique=True,
                            default='title',
                            max_length=200)
    description = models.TextField('Описание')

    class Meta:
        ordering = ('title',)
        verbose_name = 'Группа'
        verbose_name_plural = 'Группы'

    def __str__(self):
        return self.title


class Post(models.Model):
    text = models.TextField('Текст', help_text='Введите текст поста')
    pub_date = models.DateTimeField('Дата публикации', auto_now_add=True)
    author = models.ForeignKey(
        User,
        on_delete=models.CASCADE,
        related_name='posts',
        verbose_name='Автор',
    )
    group = models.ForeignKey(
        Group,
        blank=True,
        null=True,
        on_delete=models.SET_NULL,
        related_name='posts',
        verbose_name='Группа',
        help_text='Выберите группу',
    )
    image = models.ImageField(
        'Картинка',
        upload_to='posts/',
        blank=True
    )

    class Meta:
        ordering = ('-pub_date',)
        verbose_name = 'Пост'
        verbose_name_plural = 'Посты'

    def __str__(self):
        return self.text[:15]


class Comment(models.Model):
    post = models.ForeignKey(
        Post,
        on_delete=models.CASCADE,
        related_name='comments',
        verbose_name='Пост',
    )
    author = models.ForeignKey(
        User,
        on_delete=models.CASCADE,
        related_name='comments',
        verbose_name='Автор комментария',
    )
    text = models.TextField(
        'Текст комментария',
        help_text='Введите текст комментария'
    )
    created = models.DateTimeField(
        'Дата и время публикации комментария',
        auto_now_add=True
    )

    class Meta:
        ordering = ('-created',)
        verbose_name = 'Комментарий'
        verbose_name_plural = 'Комментарии'

    def __str__(self):
        return self.text[:15]


class Follow(models.Model):
    user = models.ForeignKey(
        User,
        on_delete=None,
        related_name='follower',
        verbose_name='Подписчик'
    )
    author = models.ForeignKey(
        User,
        on_delete=models.CASCADE,
        related_name='following',
        verbose_name='Автор'
    )

    class Meta:
        constraints = [
            models.UniqueConstraint(
                fields=['user', 'author'],
                name='one_following',
            ),
            models.CheckConstraint(
                check=~models.Q(user=models.F('author')),
                name='user_not_author',
            )
        ]
        verbose_name = 'Подписчик'
        verbose_name_plural = 'Подписчики'

    def __str__(self):
        return f'Подписчик: {self.user}, автор:{self.author}'

yatube/posts/forms.py
from django import forms

from .models import Comment, Post


class PostForm(forms.ModelForm):
    class Meta:
        model = Post
        fields = ('text', 'group', 'image')


class CommentForm(forms.ModelForm):
    class Meta:
        model = Comment
        fields = ('text',)

yatube/posts/views.py
from django.contrib.auth.decorators import login_required
from django.conf import settings
from django.core.paginator import Paginator
from django.shortcuts import render, get_object_or_404, redirect
# from django.views.decorators.cache import cache_page

from .forms import CommentForm, PostForm
from .models import Group, Comment, Post, User, Follow


# Главная страница
def index(request):
    template = 'posts/index.html'
    title = 'Последние обновления на сайте'
    text = 'Добро пожаловать в Yatube! Говорим обо всем на свете'
    posts = Post.objects.all()
    paginator = Paginator(posts, settings.NUMBER_OF_POSTS)
    page_number = request.GET.get('page')
    page_obj = paginator.get_page(page_number)
    context = {
        'title': title,
        'text': text,
        'page_obj': page_obj,
    }
    return render(request, template, context)


# Страница группы с сортировкой по 10 постов
def group_list(request, slug):
    group = get_object_or_404(Group, slug=slug)
    template = 'posts/group_list.html'
    posts = group.posts.all()
    paginator = Paginator(posts, settings.NUMBER_OF_POSTS)
    page_number = request.GET.get('page')
    page_obj = paginator.get_page(page_number)
    context = {
        'group': group,
        'page_obj': page_obj,
    }
    return render(request, template, context)


# Страница со списком групп
def groups(request):
    template = 'posts/groups.html'
    title = 'Информация о группах проекта Yatube'
    text = 'Список тематических групп'
    groups = Group.objects.all()
    context = {
        'title': title,
        'text': text,
        'groups': groups,
    }
    return render(request, template, context)


# Страница профиля
def profile(request, username):
    template = 'posts/profile.html'
    author = get_object_or_404(User, username=username)
    posts = Post.objects.filter(author_id=author.id)
    following = request.user.is_authenticated and author.following.exists()
    paginator = Paginator(posts, settings.NUMBER_OF_POSTS)
    page_number = request.GET.get('page')
    page_obj = paginator.get_page(page_number)
    context = {
        'author': author,
        'page_obj': page_obj,
        'following': following,
        'user': request.user
    }
    return render(request, template, context)


# Страница одного поста
def post_detail(request, post_id):
    post = get_object_or_404(Post, id=post_id)
    quantity = post.author.posts.count()
    user = request.user
    form = CommentForm(request.POST or None)
    context = {
        'user': user,
        'post': post,
        'quantity': quantity,
        'form': form,
    }
    comments = Comment.objects.filter(post_id=post_id)
    if comments:
        context.update({'comments': comments})
    return render(request, 'posts/post_detail.html', context)


# Создать пост
@login_required
def post_create(request):
    form = PostForm(
        request.POST or None,
        files=request.FILES or None,
    )
    if form.is_valid():
        form = form.save(commit=False)
        form.author = request.user
        form.save()
        return redirect('posts:profile', form.author)
    context = {
        'form': form,
        'is_edit': False
    }
    return render(request, 'posts/post_create.html', context)


# Редактировать пост
@login_required
def post_edit(request, post_id):
    post = get_object_or_404(Post, id=post_id)
    form = PostForm(
        request.POST or None,
        files=request.FILES or None,
        instance=post
    )
    if form.is_valid():
        form.save()
        return redirect('posts:post_detail', post_id)
    context = {
        'form': form,
        'is_edit': True,
        'post_id': post_id,
    }
    return render(request, 'posts/update_post.html', context)


# Оставить комментарий
@login_required
def add_comment(request, post_id):
    form = CommentForm(request.POST or None)
    if form.is_valid():
        post = Post.objects.get(pk=post_id)
        comment = form.save(commit=False)
        comment.author = request.user
        comment.post = post
        comment.save()
    return redirect('posts:post_detail', post_id=post_id)


@login_required
def follow_index(request):
    template = 'posts/follow.html'
    authors = Follow.objects.filter(user=request.user)
    following_authors = User.objects.filter(following__in=authors)
    posts = Post.objects.filter(author__in=following_authors)
    paginator = Paginator(posts, settings.NUMBER_OF_POSTS)
    page_number = request.GET.get('page')
    page_obj = paginator.get_page(page_number)
    context = {
        'page_obj': page_obj,
    }
    return render(request, template, context)


@login_required
def profile_follow(request, username):
    author = get_object_or_404(User, username=username)
    follow = Follow.objects.filter(user=request.user, author=author)
    if request.user != author and not follow:
        Follow.objects.create(
            user=request.user,
            author=author
        )
        return redirect('posts:profile', username=username)
    else:
        return redirect('posts:profile', username=username)


@login_required
def profile_unfollow(request, username):
    author = get_object_or_404(User, username=username)
    Follow.objects.filter(
        user=request.user,
        author=author
    ).delete()
    return redirect('posts:profile', username=username)

yatube/templates/posts/follow.html
{% extends "base.html" %}
{% block title %}Подписки пользователя{% endblock %}
{% block content %}
{% include 'includes/switcher.html' %}
{% load thumbnail %}
<main>
  <div class="container py-5">
    <h1>
      Лента постов:
    </h1>
    <hr>
    {% for post in page_obj %}
    <ul>
      <li>
        Автор: {{ post.author.get_full_name }}
        <a href="{% url 'posts:profile' post.author.username %}">все записи пользователя</a>
      </li>
      <li>
        Дата публикации: {{ post.pub_date|date:"d E Y" }}
      </li>
      <li>
        Группа: {{ post.group.title }}
      </li>
    </ul>
      {% thumbnail post.image "960x339" crop="center" upscale=True as im %}
      <img class="card-img my-2" src="{{ im.url }}">
      {% endthumbnail %}
    <p>{{ post.text }}</p>
    <a href="{% url 'posts:post_detail' post.id %}">подробная информация</a>
    <br>
    {% if post.group %}
    <a href="{% url 'posts:group_list' post.group.slug %}">все записи этой группы</a>
    {% endif %}
    {% if not forloop.last %}<hr>{% endif %}
    {% endfor %}
    {% include 'includes/paginator.html' %}
  </div>
</main>
{% endblock %}

yatube/templates/posts/group_list.html
{% extends "base.html" %}
{% block title %}{{ group.title }}{% endblock %}
{% block content %}
{% load thumbnail %}
<main>
  <div class="container py-5">
    <h1>{{ group.title }}</h1>
    <p>{{ group.description }}</p>
    {% for post in page_obj %}
      <article>
        <ul>
          <li>
            Автор: {{ post.author.get_full_name }}
            <a href="{% url 'posts:profile' post.author.username %}">все записи пользователя</a>
          </li>
          <li>
            Дата публикации: {{ post.pub_date|date:"d E Y" }}
          </li>
        </ul>
        {% thumbnail post.image "960x339" crop="center" upscale=True as im %}
        <img class="card-img my-2" src="{{ im.url }}">
        {% endthumbnail %}
        <p>{{ post.text }}</p>
      <a href="{% url 'posts:post_detail' post.id %}">подробная информация</a>
      </article>
        <a href="{% url 'posts:group_list' post.group.slug %}">все записи этой группы</a>
        {% if not forloop.last %}<hr>{% endif %}
    {% endfor %}
    {% include 'includes/paginator.html' %}
  </div>
</main>
{% endblock %}

yatube/templates/posts/groups.html
{% extends "base.html" %}
{% block title %}{{ title }}{% endblock %}
{% block content %}
<main>
  <div class="container py-5">
    <h1>
      {{ text }}
    </h1>
    <hr>
    {% for group in groups %}
    <ul>
      <li>
        Группа: {{ group.title }}
      </li>
    </ul>
    <p>{{ group.description }}</p>
    <a href="{% url 'posts:group_list' group.slug %}">все записи этой группы</a>
    {% if not forloop.last %}<hr>{% endif %}
    {% endfor %}
  </div>
</main>
{% endblock %}

yatube/templates/posts/index.html
{% extends "base.html" %}
{% block title %}{{ title }}{% endblock %}
{% block content %}
{% include 'includes/switcher.html' %}
{% load thumbnail %}
{% load cache %}
{% cache 20 sidebar %}
<main>
  <div class="container py-5">
    <h1>
      {{ text }}
    </h1>
    <hr>
    {% for post in page_obj %}
    <ul>
      <li>
        Автор: {{ post.author.get_full_name }}
        <a href="{% url 'posts:profile' post.author.username %}">все записи пользователя</a>
      </li>
      <li>
        Дата публикации: {{ post.pub_date|date:"d E Y" }}
      </li>
      <li>
        Группа: {{ post.group.title }}
      </li>
    </ul>
      {% thumbnail post.image "960x339" crop="center" upscale=True as im %}
      <img class="card-img my-2" src="{{ im.url }}">
      {% endthumbnail %}
    <p>{{ post.text }}</p>
    <a href="{% url 'posts:post_detail' post.id %}">подробная информация</a>
    <br>
    {% if post.group %}
    <a href="{% url 'posts:group_list' post.group.slug %}">все записи этой группы</a>
    {% endif %}
    {% if not forloop.last %}<hr>{% endif %}
    {% endfor %}
    {% include 'includes/paginator.html' %}
  </div>
</main>
{% endcache %}
{% endblock %}

yatube/templates/posts/post_create.html
{% extends "base.html" %}
{% block title %}Добавить запись{% endblock %}
{% block content %}
{% load user_filters %}
<main>
  <div class="container py-5">
    <div class="row justify-content-center">
      <div class="col-md-8 p-5">
        <div class="card">
          <div class="card-header">
            Новый пост
          </div>
          <div class="card-body">
            <form method="post"
                  action="{% url 'posts:post_create' %}"
                  enctype="multipart/form-data">
                {% csrf_token %}
                <div class="form-group row my-3 p-3">
                    <label for="id_text">
                        Текст поста
                        <span class="required text-danger" >*</span>
                    </label>
                    {{ form.text|addclass:'form-control' }}
                    <small id="id_text-help" class="form-text text-muted">
                      Текст нового поста
                    </small>
                </div>
                <div class="form-group row my-3 p-3">
                    <label for="id_image">
                        Изображение
                        <span class="required text-danger" >*</span>
                    </label>
                    {{ form.image|addclass:'form-control' }}
                    <small id="id_image-help" class="form-text text-muted">
                        Загрузить изображение
                    </small>
                </div>
                <div class="form-group row my-3 p-3">
                    <label for="id_group">
                        Тематическая группа
                    </label>
                    {{ form.group|addclass:'form-control' }}
                    <small id="id_group-help" class="form-text text-muted">
                        Группа, к которой будет относиться пост
                    </small>
                </div>
                <div class="d-flex justify-content-end">
                    <button type="submit" class="btn btn-primary">
                        {% if is_edit %}
                        Сохранить
                        {% else %}
                        Добавить
                        {% endif %}
                    </button>
                </div>
            </form>
          </div>
        </div>
      </div>
    </div>
  </div>
</main>
{% endblock %}

yatube/templates/posts/post_detail.html
{% extends "base.html" %}
{% block title %}{{  post.text|slice:":30" }}{% endblock %}
{% block content %}
{% load thumbnail %}
{% load user_filters %}
<main>
  <div class="container py-5">
    <div class="row">
      <aside class="col-12 col-md-3">
        <ul class="list-group list-group-flush">
          <li class="list-group-item">
            Дата публикации: {{ post.pub_date|date:"d E Y" }}
          </li>
            {% if post.group %}
              <li class="list-group-item">
                Группа: {{ post.group.title }}
              </li>
              <li class="list-group-item">
                <a href="{% url 'posts:group_list' post.group.slug %}">
                  все записи группы
                </a>
              </li>
            {% endif %}
            <li class="list-group-item">
              Автор: {{ post.author.get_full_name }}
            </li>
            <li class="list-group-item d-flex justify-content-between align-items-center">
              Всего постов автора: {{ quantity }}
          </li>
          <li class="list-group-item">
            <a href="{% url 'posts:profile' post.author.username %}">
              все посты пользователя
            </a>
          </li>
        </ul>
      </aside>
      <article class="col-12 col-md-9">
        {% thumbnail post.image "960x339" crop="center" upscale=True as im %}
        <img class="card-img my-2" src="{{ im.url }}">
        {% endthumbnail %}
        <p>{{ post.text }}</p>
        {% if post.author == user %}
        <a class="btn btn-primary" href="{% url 'posts:post_edit' post.id %}">
          редактировать запись
        </a>
        {% endif %}
        {% if user.is_authenticated %}
        <div class="card my-4">
          <h5 class="card-header">Добавить комментарий:</h5>
          <div class="card-body">
            <form method="post" action="{% url 'posts:add_comment' post.id %}">
              {% csrf_token %}
              <div class="form-group mb-2">
              {{ form.text|addclass:"form-control" }}
              </div>
              <button type="submit" class="btn btn-primary">Отправить</button>
            </form>
          </div>
        </div>
        {% endif %}
        {% for comment in comments %}
          <div class="media mb-4">
            <div class="media-body">
              <h5 class="mt-0">
                <a href="{% url 'posts:profile' comment.author.username %}">
                  {{ comment.author.username }}
                </a>
              </h5>
                <p>
                 {{ comment.text }}
                </p>
              </div>
            </div>
        {% endfor %}
      </article>
    </div>
  </div>
</main>
{% endblock %}

yatube/templates/posts/profile.html
{% extends "base.html" %}
{% block title %}Профайл пользователя {{ author }}{% endblock %}
{% block content %}
{% load thumbnail %}
<main>
  <div class="container py-5">
    <div class="mb-5">
      <h1>Все посты пользователя {{ author.get_full_name }} ({{ author.username }})</h1>
      <h3>Всего постов: {{ page_obj.paginator.count }}</h3>
      {% if author != user %}
        {% if following %}
            <a
              class="btn btn-lg btn-light"
              href="{% url 'posts:profile_unfollow' author.username %}" role="button"
            >
              Отписаться
            </a>
        {% else %}
            <a
              class="btn btn-lg btn-primary"
              href="{% url 'posts:profile_follow' author.username %}" role="button"
            >
              Подписаться
            </a>
        {% endif %}
      {% endif %}
    </div>
    <article>
      <hr>
      {% for post in page_obj %}
      <ul>
        <li>
          Дата публикации: {{ post.pub_date|date:"d E Y" }}
        </li>
      </ul>
      {% thumbnail post.image "960x339" crop="center" upscale=True as im %}
      <img class="card-img my-2" src="{{ im.url }}">
      {% endthumbnail %}
      <p>{{ post.text }}</p>
    </article>
    <a href="{% url 'posts:post_detail' post.id %}">подробная информация</a>
    <br>
    {% if post.group %}
    <a href="{% url 'posts:group_list' post.group.slug %}">все записи группы</a>
    {% endif %}
    {% if not forloop.last %}<hr>{% endif %}
    {% endfor %}
    {% include 'includes/paginator.html' %}
  </div>
</main>
{% endblock %}

yatube/templates/posts/update_post.html
{% extends "base.html" %}
{% block title %}Редактировать запись{% endblock %}
{% block content %}
{% load user_filters %}
<main>
  <div class="container py-5">
    <div class="row justify-content-center">
      <div class="col-md-8 p-5">
        <div class="card">
          <div class="card-header">
            Редактировать пост
          </div>
          <div class="card-body">
            <form method="post"
                  enctype="multipart/form-data"
                  action="{% url 'posts:post_edit' post_id %}">
              {% csrf_token %}
              <div class="form-group row my-3 p-3">
                    <label for="id_text">
                        Текст поста
                        <span class="required text-danger" >*</span>
                    </label>
                    {{ form.text|addclass:'form-control' }}
                    <small id="id_text-help" class="form-text text-muted">
                      Текст с изменениями для поста
                    </small>
                </div>
                <div class="form-group row my-3 p-3">
                    <label for="id_image">
                        Изображение
                        <span class="required text-danger" >*</span>
                    </label>
                    {{ form.image|addclass:'form-control' }}
                    <small id="id_image-help" class="form-text text-muted">
                        Загрузить изображение
                    </small>
                </div>
                <div class="form-group row my-3 p-3">
                    <label for="id_group">
                        Тематическая группа
                    </label>
                    {{ form.group|addclass:'form-control' }}
                    <small id="id_group-help" class="form-text text-muted">
                        Группа, к которой будет относиться пост
                    </small>
                </div>
                <div class="d-flex justify-content-end">
                    <button type="submit" class="btn btn-primary">
                        {% if is_edit %}
                        Сохранить
                        {% else %}
                        Добавить
                        {% endif %}
                    </button>
                </div>
            </form>
          </div>
        </div>
      </div>
    </div>
  </div>
</main>
{% endblock %}